name: CI/CD Pipeline
on:
  push:
    branches: ["**"] # Lint runs on all branches
  pull_request:
    branches: ["**"] # Lint runs on PRs to any branch
  workflow_dispatch: # Manual deploy trigger (only works on main)

jobs:
  lint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - uses: golangci/golangci-lint-action@v6
        with:
          version: latest
      - run: make lint

  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    # Only deploy on main branch AND only when manually triggered
    if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
    needs: lint
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GOOGLE_CLOUD_KEYFILE_JSON: ${{ secrets.GOOGLE_CLOUD_KEYFILE_JSON }}
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ env.GOOGLE_CLOUD_KEYFILE_JSON }}
      - run: gcloud auth configure-docker gcr.io --quiet
      - run: make deploy
